@url = http://localhost:5000

###

POST {{url}}/api/report/template HTTP/1.1
Content-Type: application/json

{
  "report" : {
    "Id": "",
    "Title": "Title",
    "Questionnaires": [
      {
        "Sections": [
          {
            "Title": null,
            "Order": 0,
            "Repeatable": false,
            "Questions": [
              { "QuestionText": "question 1", "InputType": 6 },
              { "QuestionText": "question 2", "InputType": 10 }
            ]
          }
        ],
        "Title": null,
        "Order": 0
      }
    ],
    "Tables": []
  }
}

###

GET {{url}}/api/report/template/info HTTP/1.1

###

GET {{url}}/api/report/template/c19b4b52-bd4e-404e-8237-1317eb34859a HTTP/1.1