version: "3.1"

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    hostname: "rabbitmq"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "5672:5672"
      - "15672:15672"

  is_storage:
    image: mongo
    container_name: is_storage
    restart: always
    ports:
      - "27017:27017"

  is_storage_gui:
    image: mongo-express
    container_name: is_storage_gui
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - is_storage
    environment:
      - ME_CONFIG_MONGODB_SERVER=is_storage
      - ME_CONFIG_MONGODB_PORT=27017
