version: "3.1"

services:

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    hostname: "rabbitmq"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "5672:5672"
      - "15672:15672"

  scheduler_storage:
    image: mongo
    container_name: scheduler_storage
    restart: always
    ports:
      - "27017:27017"
  
  scheduler_storage_gui:
    image: mongo-express
    container_name: scheduler_storage_gui
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - scheduler_storage
    environment:
      - ME_CONFIG_MONGODB_SERVER=scheduler_storage
      - ME_CONFIG_MONGODB_PORT=27017
