version: "3.1"

services:
  rss_storage:
    image: mongo
    container_name: rss_storage
    restart: always
    ports:
      - "27018:27017"

  rss_storage_gui:
    image: mongo-express
    container_name: rss_storage_gui
    restart: always
    ports:
      - "8100:8081"
    depends_on:
      - rss_storage
    environment:
      - ME_CONFIG_MONGODB_SERVER=rss_storage
      - ME_CONFIG_MONGODB_PORT=27017

  rss:
    build: .
    restart: always
    ports:
      - "5100:5000"
      - "5101:5001"
    container_name: rss
    depends_on:
      - rss_storage
    environment: 
      - ASPNETCORE_ENVIRONMENT=dev

