version: "3.1"

services:

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    hostname: "rabbitmq"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "5672:5672"
      - "15672:15672"

  rp_storage:
    image: mongo
    container_name: rp_storage
    restart: always
    ports:
      - "27017:27017"
  
  rp_storage_gui:
    image: mongo-express
    container_name: rp_storage_gui
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - rp_storage
    environment:
      - ME_CONFIG_MONGODB_SERVER=rp_storage
      - ME_CONFIG_MONGODB_PORT=27017
  
  rcs_storage:
    image: mongo
    container_name: rcs_storage
    restart: always
    ports:
      - "27018:27017"
    
  rcs_storage_gui:
    image: mongo-express
    container_name: rcs_storage_gui
    restart: always
    ports:
      - "8181:8081"
    depends_on:
      - rcs_storage
    environment: 
      - ME_CONFIG_MONGODB_SERVER=rcs_storage
      - ME_CONFIG_MONGODB_PORT=27017
    
  rcs:
    image: focus_constructor:latest
    restart: always
    ports:
      - "5100:5000"
    container_name: rcs
    depends_on:
      - rcs_storage
      - rabbitmq
    environment: 
      - ASPNETCORE_ENVIRONMENT=dev
      - ASPNETCORE_URLS=http://*:5000

  rss_storage:
    image: mongo
    container_name: rss_storage
    restart: always
    ports:
      - "27019:27017"

  rss_storage_gui:
    image: mongo-express
    container_name: rss_storage_gui
    restart: always
    ports:
      - "8281:8081"
    depends_on:
      - rss_storage
    environment:
      - ME_CONFIG_MONGODB_SERVER=rss_storage
      - ME_CONFIG_MONGODB_PORT=27017

  rss:
    image: focus_scheduler:latest
    restart: always
    ports:
      - "5200:5000"
    container_name: rss
    depends_on:
      - rss_storage
      - rabbitmq
    environment: 
      - ASPNETCORE_ENVIRONMENT=dev
      - ASPNETCORE_URLS=http://*:5000