version: "3.1"

services:

  processor_storage:
    image: mongo
    container_name: processor_storage
    restart: always
    ports:
      - "27017:27017"
  
  processor_storage_gui:
    image: mongo-express
    container_name: rp_storage_gui
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - processor_storage
    environment:
      - ME_CONFIG_MONGODB_SERVER=processor_storage
      - ME_CONFIG_MONGODB_PORT=27017