version: "3.1"

services:
  rcs_storage:
    image: mongo
    container_name: rcs_storage
    restart: always
    ports:
      - "27017:27017"

  rcs_storage_gui:
    image: mongo-express
    container_name: rcs_storage_gui
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - rcs_storage
    environment: 
      - ME_CONFIG_MONGODB_SERVER=rcs_storage
      - ME_CONFIG_MONGODB_PORT=27017

  rcs:
    image: focus_constructor:latest
    restart: always
    ports:
      - "5000:5000"
    container_name: rcs
    depends_on:
      - rcs_storage
    environment: 
      - ASPNETCORE_ENVIRONMENT=dev
      - ASPNETCORE_URLS=http://*:5000
