version: "3.1"

services:

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    hostname: "rabbitmq"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "5672:5672"
      - "15672:15672"
    
  rcs_storage:
    image: mongo
    container_name: rcs_storage
    restart: always
    ports:
      - "27017:27017"
    
  rss_storage:
    image: mongo
    container_name: rss_storage
    restart: always
    ports:
      - "27018:27017"
  
  is_storage:
    image: mongo
    container_name: is_storage
    restart: always
    ports:
      - "27019:27017"

  rcs:
    image: focus_constructor:latest
    restart: always
    ports:
      - "5000:5000"
    container_name: rcs
    depends_on:
      - rcs_storage
    environment:
      - ASPNETCORE_ENVIRONMENT=dev
      - ASPNETCORE_URLS=http://*:5000

  rss:
    image: focus_scheduler:latest
    restart: always
    ports:
      - "5100:5000"
    container_name: rss
    depends_on:
      - rss_storage
      - rabbitmq
    environment:
      - ASPNETCORE_ENVIRONMENT=dev
      - ASPNETCORE_URLS=http://*:5000

  daily:
    image: focus_newdayemitter:latest
    container_name: nde
    restart: always
    depends_on: 
      - rabbitmq
    environment: 
      - DOTNET_ENVIRONMENT=dev

  is:
    image: focus_identity:latest
    restart: always
    ports:
      - "5200:5000"
    container_name: is
    depends_on: 
      - is_storage
    environment: 
      - ASPNETCORE_ENVIRONMENT=dev
      - ASPNETCORE_URLS=http://*:5000
