version: "3.1"

services:

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    hostname: "rabbitmq"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "5672:5672"
      - "15672:15672"
    
# MongoDB databases

  constructor_storage:
    image: mongo
    container_name: constructor_storage
    restart: always
    
  scheduler_storage:
    image: mongo
    container_name: scheduler_storage
    restart: always
  
  identity_storage:
    image: mongo
    container_name: identity_storage
    restart: always

  processor_storage:
    image: mongo
    container_name: processor_storage
    restart: always

# services

  constructor:
    image: focus.constructor:latest
    restart: always
    hostname: "constructor"
    ports:
      - "5000:5000"
    container_name: constructor
    depends_on:
      - constructor_storage
    environment:
      - ASPNETCORE_ENVIRONMENT=dev
      - ASPNETCORE_URLS=http://*:5000

  scheduler:
    image: focus.scheduler:latest
    restart: always
    hostname: "scheduler"
    ports:
      - "5100:5000"
    container_name: scheduler
    depends_on:
      - scheduler_storage
      - rabbitmq
    environment:
      - ASPNETCORE_ENVIRONMENT=dev
      - ASPNETCORE_URLS=http://*:5000

  automator:
    image: focus.automator:latest
    container_name: automator
    restart: always
    depends_on: 
      - rabbitmq
    environment: 
      - DOTNET_ENVIRONMENT=dev

  identity:
    image: focus.identity:latest
    restart: always
    hostname: "identity"
    ports:
      - "5200:5000"
    container_name: identity
    depends_on: 
      - identity_storage
    environment: 
      - ASPNETCORE_ENVIRONMENT=dev
      - ASPNETCORE_URLS=http://*:5000

  processor:
    image: focus.processor:latest
    restart: always
    hostname: "processor"
    ports: 
      - "5300:5000"
    container_name: processor
    depends_on: 
      - processor_storage
    environment: 
      - ASPNETCORE_ENVIRONMENT=dev
      - ASPNETCORE_URLS=http://*:5000
