# basic focus_common image
FROM mcr.microsoft.com/dotnet/core/sdk:3.1

WORKDIR /app

COPY ./Focus.Application.Common ./Focus.Application.Common
COPY ./Focus.Core.Common ./Focus.Core.Common
COPY ./Focus.Infrastructure.Common ./Focus.Infrastructure.Common
COPY ./Focus.Api.Common ./Focus.Api.Common